version: "3.8"
# volumes:
#  certs:
#    driver: local
#  esdata01:
#    driver: local
#  kibanadata:
#    driver: local
#  metricbeatdata01:
#    driver: local
#  filebeatdata01:
#    driver: local
#  logstashdata01:
#    driver: local

# networks: {elastic_network: {}}


services:

  elasticsearch01:
    # container_name: es1
    # hostname: es1
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./shared_folder
        target: /shared_folder
      # - ${ELASTICSEARCH_DATA:-/data}/elasticsearch01:/usr/share/elasticsearch/data
      
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch01
      - discovery.seed_hosts=elasticsearch02,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-4g} -Xmx${ES_HEAP_SIZE:-4g}"
    # networks: ['elastic_network']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elasticsearch02:
    # container_name: es2
    # hostname: es2
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./shared_folder
        target: /shared_folder
      # - ${ELASTICSEARCH_DATA:-/data}/elasticsearch02:/usr/share/elasticsearch/data
      

    environment:
      - node.name=elasticsearch02
      - discovery.seed_hosts=elasticsearch01,elasticsearch03
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-4g} -Xmx${ES_HEAP_SIZE:-4g}"
        
    # networks: ['elastic_network']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30
    ulimits:
      memlock:
        soft: -1
        hard: -1
  
    depends_on:
      - elasticsearch01

  elasticsearch03:
    # container_name: es3
    # hostname: es3
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./shared_folder
        target: /shared_folder
      # - ${ELASTICSEARCH_DATA:-/data}/elasticsearch02:/usr/share/elasticsearch/data
      

    environment:
      - node.name=elasticsearch03
      - discovery.seed_hosts=elasticsearch01,elasticsearch02
      - cluster.initial_master_nodes=elasticsearch01,elasticsearch02,elasticsearch03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-4g} -Xmx${ES_HEAP_SIZE:-4g}"
    
    # networks: ['elastic_network']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30
    ulimits:
      memlock:
        soft: -1
        hard: -1

    depends_on:
      - elasticsearch01      
      - elasticsearch02       



  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    environment:
      # - 'ELASTICSEARCH_HOSTS=["http://elasticsearch1:9200","http://elasticsearch2:9200","http://elasticsearch3:9200"]'
      # - "SERVER_NAME=localhost"
      # - "SERVER_BASEPATH="
      # - "SERVER_PUBLICBASEURL=http://localhost:5601"
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - xpack.encryptedSavedObjects.encryptionKey=2fb03f21994196d08cfe23f2292cf971
      - xpack.reporting.encryptionKey=082e5568fac3c9328183d9884e9d0510
      - xpack.security.encryptionKey=2dabcece5377a8e49271b7e3f754c614
    # networks: ['elastic_network']
    ports:
      - 5601:5601
    depends_on:
      elasticsearch01:
        condition: service_healthy
      elasticsearch02:
        condition: service_healthy
      elasticsearch03:
        condition: service_healthy

  web_server:
    build:
      context: ./nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # networks: ['elastic_network']
    depends_on:
      elasticsearch01:
        condition: service_healthy
      elasticsearch02:
        condition: service_healthy
      elasticsearch03:
        condition: service_healthy

  cerebro:
    build:
      context: ./cerebro
    restart: always
    # networks: ['elastic_network']
    # ports:
    #   - 9000:9000
    volumes:
      - ./cerebro/application.conf:/opt/cerebro/conf/application.conf
    depends_on:
      elasticsearch01:
        condition: service_healthy
      elasticsearch02:
        condition: service_healthy
      elasticsearch03:
        condition: service_healthy

